version: '3'

services:

  toolmarket-client-app:
    container_name: toolmarket-client-app
    restart: 'no'
    networks:
      - web
    env_file:
      - ./.env
    stdin_open: true
    image: toolmarket-client-app-image
    build: ./app
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src

networks:
  web:
    external:
      name: ${TRAEFIK_NETWORK}
